# Generated by Django 4.1.6 on 2023-09-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='data',
            new_name='swiss_data',
        ),
        migrations.AddField(
            model_name='userdata',
            name='knockout_data',
            field=models.JSONField(default=dict),
        ),
    ]
